# Generated by Django 2.2.5 on 2021-11-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('question', models.CharField(max_length=500)),
                ('question_nlp', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=1000)),
                ('answer_bytes', models.CharField(max_length=100)),
                ('time_proc_npl_final', models.CharField(max_length=100)),
                ('time_proc_ws_final', models.CharField(max_length=100)),
                ('time_req_final', models.CharField(max_length=100)),
                ('time_bs4_final', models.CharField(max_length=100)),
            ],
        ),
    ]
